language: node_js
sudo: required

node_js:
- '0.12'

cache:
  directories:
  - node_modules

install:
- npm install

script:
- npm test

deploy:
  provider: heroku
  api_key:
    secure: XcMUQIVQPYczqw6bc54Chtby7fFhtRTF9xkfxYaqwH78DFONSHIwzBC40bhZ13tvBLgogcTgSpzCsqf6CpE5C9ZzQuMyPxakyl93QKMfzglUicEJX7EkGGtBwBiOJiu0U4L1eXM1ld2U7oKUHIHSmHxZfyhJdeBCumfm7Ix4O6rD7PFOYIqCwgRFLx6WreUB9ih+kruo5qcABTh0bfJ6W1DqJmKzRh+EVnjDtSQbRPyjus3iDbptrm9gh5gdbj74DhuGMOjhJr2O0VWu+Ny/yH+HA9Foji3fC790EvAGsLCORYrNlD6Wd1wsIajnhglOuQz6vPvxMhB5b7h+q82mOkuqg+KK3oNzFOjtoBCNHv371O/wMp4SlowUAM39a0OeLl6qL4EtisLiJMWYMXcDykD4eRaGtcuM0V6YmuxCe5PzwgqxaHhJCI+bZYOjSAiORAVJxWxHMSamX0xzvk9HUu7LRD5044qyyuNlujk8pinZ7dAnra8dDUThpUUv3M01d50JpkCCtJQwOQfgwtH1MVzJNLOgOugyCtJQHYnCpsbb2drDMJv4pN6F88XuoaFzCZc2QD6pB606U9v7m0ul6aNFCB58Nq54fdlYTkTd1ZUCWL45zaIGyo1vwNnOyq0y1pfEAqUnRKzjK05mLRltFbhpQhOienGDJqJJQK9grQQ=
  app: vast-headland-9951
